# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose port 3000
EXPOSE 80
# Set environment variables
ENV PORT=80

# Start the server with nodemon
CMD ["npm", "run", "start"]

# docker build -t cupkido/fullstack6 .
# docker run -p 80:80 --name fullstack6 cupkido/fullstack6